#!/usr/bin/env python
import sys
from supp import linter

for fname in sys.argv[1:]:
    for e, msg, line, col in linter.lint(None, open(fname).read(), fname):
        print('{}:{}:{}\t{}\t{}'.format(fname, line, col, e, msg))
