#!/usr/bin/env python
import sys
from supp import linter

for fname in sys.argv[1:]:
    errors = linter.lint(None, open(fname).read(), fname)
    for e, msg, line, col, flow in errors:
        print('{}:{}:{}\t{}\t{}\t{} {}'.format(
            fname, line, col, e, msg, flow, flow.scope))
